# Generated by Django 4.2.10 on 2024-02-12 10:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_raw_material', models.CharField(max_length=256)),
                ('UoM', models.CharField(max_length=100)),
                ('previous_supplier', models.CharField(max_length=256)),
                ('estimated_delivery_time', models.CharField(max_length=256)),
                ('vendor_location', models.CharField(max_length=256)),
                ('minimum_stock_required_for_15days', models.CharField(max_length=100)),
                ('current_stock', models.CharField(max_length=100)),
                ('total_quantity_required', models.CharField(max_length=100)),
                ('last_purchase_price', models.CharField(blank=True, max_length=100, null=True)),
                ('last_purchase_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vendor_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_raw_material', models.CharField(max_length=256)),
                ('purchase_rate_per_kg', models.CharField(max_length=256)),
                ('delivery', models.CharField(max_length=256)),
                ('payment_terms', models.CharField(max_length=256)),
                ('freight', models.CharField(max_length=256)),
                ('gst', models.CharField(max_length=256)),
                ('name_of_vendor', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('GST', models.CharField(max_length=100)),
                ('bank_details', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.jpeg', upload_to='profile_pics')),
                ('employee_id', models.CharField(blank=True, max_length=256)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, choices=[('factory', 'Factory'), ('accounts', 'Accounts'), ('head_office', 'Head Office'), ('super_admin', 'Super Admin')], max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
